"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.frontendArchitectureTraining = {
    name: "Architektura aplikacji frontendowych",
    description: "Celem szkolenia jest nauczenie uczestnik\u00F3w w jaki spos\u00F3b tworzy\u0107 skalowalne architektury aplikacji oraz jak wygl\u0105daj\u0105 nowoczesne narz\u0119dzia JS umo\u017Cliwiaj\u0105ce tworzenie i utrzymywanie du\u017Cych system\u00F3w frontendowych.",
    profile: "\nSzkolenie adresowane jest do programist\u00F3w znaj\u0105cych j\u0119zyk JavaScript.",
    duration: 3,
    list: [
        "Podej\u015Bcie obiektowe i funkcyjne",
        "Paradygmaty programowania: imperatywny, deklaratywny, reaktywny",
        "Asynchroniczno\u015B\u0107:",
        "Events and custom events",
        "Generatory",
        "Async/await",
        "Strumienie",
        "ES6 Observables",
        "Communicating sequential processes (CSP)",
        "Domain Driven Design",
        "Test-driven development",
        "Modele architektoniczne:",
        "Model-view-controller",
        "Model-view-viewmodel",
        "Model-view-presenter",
        "Model-view-intent",
        "CQRS",
        "Flux",
        "Redux",
        "Static analysis tools",
        "Architektura informacji",
        "Podstawy UX",
        "Accessibility",
        "Semantic Web",
        "Debugowanie",
        "Developer tools",
        "Optymalizacja",
        "Critical render path",
        "Progressive Web App",
        "Web workers",
        "Service workers"
    ],
    skills: "\nPo uko\u0144czonym szkoleniu uczestnicy b\u0119d\u0105 znali zagadnienia zwi\u0105zane z architektur\u0105 aplikacji. Poznaj\u0105 r\u00F3wnie\u017C szereg narz\u0119dzi, kt\u00F3re pozwalaj\u0105 na du\u017Co \u0142atwiejsze pisanie program\u00F3w frontendowych \n\n"
};
